version: "3.7"
services:
    db:
        image: stephaneklein/postgres-with-walg:12.2-alpine-walg0.2.15
        restart: unless-stopped
        volumes:
            - ${POSTGRES_VOLUME_DATA}:/var/lib/postgresql/data
            - ${POSTGRES_VOLUME_KEYS}:/keys/
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}

    app:
        image: mattermost/mattermost-prod-app:5.21.0
        restart: unless-stopped
        user: root
        volumes:
            - ./config:/mattermost/config:rw
            - ${MATTERMOST_APP_VOLUME_DATA}:/mattermost/data:rw
            - ${MATTERMOST_APP_VOLUME_LOG}:/mattermost/logs:rw
        environment:
            MM_SQLSETTINGS_DATASOURCE: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable&connect_timeout=10

    web:
        image: mattermost/mattermost-prod-web:5.20.2
        restart: unless-stopped
        ports:
            - "8080:80"
        environment:
            MATTERMOST_ENABLE_SSL: "false"
            # This parameters are used by nginx-proxy (https://github.com/nginx-proxy/nginx-proxy)
            VIRTUAL_HOST: ${MATTERMOST_VIRTUAL_HOST}
            LETSENCRYPT_HOST: ${MATTERMOST_LETSENCRYPT_HOST}
            LETSENCRYPT_EMAIL: ${MATTERMOST_LETSENCRYPT_EMAIL}

networks:
    default:
        name: mattermost-prod