version: "3.7"
services:
    db:
        volumes:
            - ${POSTGRES_VOLUME_KEYS}:/keys/
        environment:
            PGHOST: /var/lib/postgresql/data
            PGUSER: postgres
            PGDATABASE: ${POSTGRES_DB}
            PGPASSWORD: ${POSTGRES_PASSWORD}
            AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
            AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
            WALE_S3_PREFIX: ${WALE_S3_PREFIX}
            AWS_ENDPOINT: ${AWS_ENDPOINT}
            AWS_S3_FORCE_PATH_STYLE: "true"
            AWS_REGION: ${AWS_REGION}
            WALG_COMPRESSION_METHOD: brotli
            ARCHIVE_MODE: 'off'
            ARCHIVE_TIMEOUT: 60
            WALG_PGP_KEY_PATH: ${WALG_PGP_PUB_KEY_PATH}
